replicasCount: 1

image:
  url: acrcybergoatzprod.azurecr.io/elasticsearch-service-service
  tag: v1.2.2

resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

environments:
  SERVICE_PRECONDITION: uag-service:8084

mounts:
  elasticsearch-service:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: false
    type:
      configMap:
        name: elasticsearch-service-configmap
  tls:
    extension: .crt
    mountPath: /srv/
    isOneFile: true
    subPath: false
    type:
      secret:
        secretName: cybergoatz-certs
