{{- $headHost := .Values.global.headHost -}}
{{- $authHost := .Values.global.authHost | default $headHost -}}
{{- $realm := .Values.realm | default .Values.global.keycloakRealm -}}
{{- $publicPaths := list (printf "/keycloak/realms/%s" $realm) "/keycloak/resources" "/keycloak/js" "/keycloak/robots.txt" -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-ingressroute
  labels: {{- include "common.labels" (dict "name" .name "chart" $.Chart "release" $.Release "extraLabels" .extraLabels) | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- if .Values.publicIngress.exposeAdmin }}
    - kind: Rule
      {{- if mustRegexMatch "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.){3}(25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)$" $authHost }}
      match: PathPrefix(`/keycloak`)
      {{- else }}
      match: Host(`{{ $authHost }}`) && PathPrefix(`/keycloak`)
      {{- end }}
      services:
        - kind: Service
          name: keycloak-service
          port: 8080
    {{- else }}
    {{- range $path := $publicPaths }}
    - kind: Rule
      {{- if mustRegexMatch "^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.){3}(25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)$" $authHost }}
      match: PathPrefix(`{{ $path }}`)
      {{- else }}
      match: Host(`{{ $authHost }}`) && PathPrefix(`{{ $path }}`)
      {{- end }}
      services:
        - kind: Service
          name: keycloak-service
          port: 8080
    {{- end }}
    {{- end }}
  tls:
    secretName: {{ .Values.global.tlsSecretName }}
    domains:
    - main: {{ $authHost }}
