{{- $adminSecretName := printf "%s-initial-admin" .Values.name -}}
{{- $existingAdminSecret := lookup "v1" "Secret" .Release.Namespace $adminSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $adminSecretName }}
type: kubernetes.io/basic-auth
data:
  username: {{- if and $existingAdminSecret (hasKey $existingAdminSecret.data "username") }} {{ index $existingAdminSecret.data "username" | quote }}{{- else }} {{ .Values.keycloakAdmin | b64enc | quote }}{{- end }}
  password: {{- if and $existingAdminSecret (hasKey $existingAdminSecret.data "password") }} {{ index $existingAdminSecret.data "password" | quote }}{{- else }} {{ .Values.keycloakPassword | b64enc | quote }}{{- end }}
