apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-initial-admin
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.keycloakAdmin | quote }}
  password: {{ .Values.keycloakPassword | quote }}
