{{- $cyberGoatzFrontendUrls := list -}}
{{- if .Values.cyberGoatzFrontendUrls -}}
{{- range .Values.cyberGoatzFrontendUrls -}}
{{- $cyberGoatzFrontendUrls = append $cyberGoatzFrontendUrls (trimSuffix "/" .) -}}
{{- end -}}
{{- else -}}
{{- $cyberGoatzFrontendUrls = append $cyberGoatzFrontendUrls (trimSuffix "/" (.Values.cyberGoatzFrontendUrl | default "http://localhost:3000")) -}}
{{- end -}}
{{- $learnerClientId := .Values.learnerClient.clientId | default "cybergoatz-learner" -}}
{{- $learnerClientSecret := required "crczp-keycloak.learnerClient.clientSecret is required" .Values.learnerClient.clientSecret -}}
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: cybergoatz-learner
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  client:
    attributes:
      pkce.code.challenge.method: S256
      post.logout.redirect.uris: +
    clientId: {{ $learnerClientId | quote }}
    clientAuthenticatorType: client-secret
    defaultClientScopes:
      - email
      - profile
      - openid
    directAccessGrantsEnabled: false
    implicitFlowEnabled: false
    name: "CyberGoatz"
    optionalClientScopes:
      - offline_access
    protocol: openid-connect
    publicClient: false
    baseUrl: "{{ first $cyberGoatzFrontendUrls }}"
    redirectUris:
      {{- range $frontendUrl := $cyberGoatzFrontendUrls }}
      - "{{ $frontendUrl }}"
      - "{{ $frontendUrl }}/*"
      - "{{ $frontendUrl }}/api/auth/callback/keycloak"
      - "{{ $frontendUrl }}/api/auth/callback/keycloak-register"
      {{- end }}
    secret: {{ $learnerClientSecret | quote }}
    standardFlowEnabled: true
    webOrigins:
      {{- range $frontendUrl := $cyberGoatzFrontendUrls }}
      - "{{ $frontendUrl }}"
      {{- end }}
