replicasCount: 1

image:
  url: cybergoatz.azurecr.io/cybergoatz-service
  tag: v1.0.0
  pullPolicy: IfNotPresent

database:
  synchronize: true

publicTraining:
  timeoutMs: 1500

htb:
  apiUrl: https://labs.hackthebox.com/api/v4
  profileBaseUrl: https://app.hackthebox.com/public/users
  tokenEncryptionKey: change-me-generate-32-byte-secret
  timeoutMs: 5000

resources: {}
