{{- $trainingServiceClientSecret := dig "serviceAccounts" "training" "clientSecret" .Values.sandboxServiceAccount.clientSecret .Values.global }}
apiVersion: v1
kind: Secret
metadata:
  name: training-service-service-account
  labels: {{- include "common.labels" (dict "name" .Values.global.services.training.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ $trainingServiceClientSecret | quote }}
