replicasCount: 1

image:
  url: cybergoatz.azurecr.io/admin-frontend
  tag: v1.0.4

mounts:
  config:
    extension: .json
    mountPath: /app/assets/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: angular-frontend-configmap

releaseVersion: v2026.02
