replicasCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

image:
  url: acrcybergoatzprod.azurecr.io/admin-frontend
  tag: v1.0.6

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi

mounts:
  config:
    extension: .json
    mountPath: /app/assets/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: angular-frontend-configmap

releaseVersion: v2026.02
