replicasCount: 1

image:
  url: cybergoatz.azurecr.io/admin-frontend
  tag: v1.0.4

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 128Mi

mounts:
  config:
    extension: .json
    mountPath: /app/assets/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: angular-frontend-configmap

releaseVersion: v2026.02
