apiVersion: v1
kind: Secret
metadata:
  name: guacamole-service-secrets
  labels: {{- include "common.labels" (dict "name" .Values.global.services.guacamole.name "chart" .Chart "release" .Release "extraLabels" .Values.extraLabels) | nindent 4 }}
type: Opaque
data:
  ticket-encryption-key: {{ .Values.ticketEncryptionKey | b64enc | quote }}
