name: keycloak

db:
  database: keycloak
  username: keycloak

grafanaClientSecret:

keycloakAdmin: admin
keycloakPassword:

development: false

realm: CRCZP

realmConfig:
  registrationAllowed: true
  registrationEmailAsUsername: false
  rememberMe: true
  verifyEmail: false
  resetPasswordAllowed: true
