name: keycloak

db:
  database: keycloak
  username: keycloak

grafanaClientSecret:
cyberGoatzFrontendUrl: http://localhost:3000

keycloakAdmin: admin
keycloakPassword:
realmSync:
  enabled: true
  image: quay.io/keycloak/keycloak:25.0.1
  imagePullPolicy: IfNotPresent

development: false

realm: CRCZP

theme:
  enabled: true
  name: cyber-goatz
  disableCache: true
  writableDevMount: true

realmConfig:
  registrationAllowed: true
  registrationEmailAsUsername: false
  rememberMe: true
  verifyEmail: false
  resetPasswordAllowed: true
  termsAndConditions:
    enabled: true
  passwordPolicy:
  smtp:
    enabled: false
    host:
    port: 587
    from:
    fromDisplayName:
    replyTo:
    replyToDisplayName:
    envelopeFrom:
    ssl: false
    starttls: true
    auth: true
    user:
    password:
  googleIdentityProvider:
    enabled: false
    alias: google
    displayName: Google
    trustEmail: true
    storeToken: false
    addReadTokenRoleOnCreate: false
    firstBrokerLoginFlowAlias: first broker login
    clientId:
    clientSecret:
    hostedDomain:
