replicasCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

image:
  url: acrcybergoatzprod.azurecr.io/adaptive-smart-assistant-service
  tag: v1.2.2

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

mounts:
  adaptive-smart-assistant:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: smart-assistant-configmap

databasePool:
  maximumPoolSize: 3
  minimumIdle: 1
  connectionTimeout: 10000
  idleTimeout: 600000
  maxLifetime: 1800000
  leakDetectionThreshold: 0
