replicasCount: 1

image:
  url: cybergoatz.azurecr.io/adaptive-smart-assistant-service
  tag: v1.2.1

mounts:
  adaptive-smart-assistant:
    extension: .properties
    mountPath: /app/etc/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: smart-assistant-configmap

databasePool:
  maximumPoolSize: 3
  minimumIdle: 1
  connectionTimeout: 10000
  idleTimeout: 600000
  maxLifetime: 1800000
  leakDetectionThreshold: 0
