replicasCount: 1

image:
  url: cybergoatz.azurecr.io/mitre-technique-service
  tag: v1.1.1

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

djangoSecretKey:

environments:
  SERVICE_PRECONDITION: uag-service:8084

secretEnvironments:
  DJANGO_SECRET_KEY:
    secretName: mitre-service-secret
    secretKey: django-secret-key

mounts:
  config:
    extension: .yml
    mountPath: /app/
    isOneFile: true
    subPath: true
    type:
      configMap:
        name: mitre-service-configmap

redis:
  db: 1

fileStorage: crczp/mitre_matrix_visualizer_app/templates/
